### ISSUE TITLE
Run Local Tests not turning green after test passed in Xcode

### ISSUE THREAD

**Issue by thegerscheffect** [learn-co-curriculum/swift-HelloToTheUniverse-lab#15]

**Comment by JimCampagno** [comment]
There were changes made to this lab yesterday to make these lights work. Instead of having you go back to get this version, I would suggest moving forward. When you reach a lab in the future that contains tests (where your lights should light up), at that point if you find that the lights aren't lighting up I would raise another issue.

Sorry about that!

@thegerscheffect
